//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tbl_City
    {
        public LU_tbl_City()
        {
            this.tbl_Post = new HashSet<tbl_Post>();
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public string CityID { get; set; }
        public string CountryID { get; set; }
        public string CityName { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual LU_tbl_Country LU_tbl_Country { get; set; }
        public virtual ICollection<tbl_Post> tbl_Post { get; set; }
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
