//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tbl_Country
    {
        public LU_tbl_Country()
        {
            this.LU_tbl_City = new HashSet<LU_tbl_City>();
        }
    
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual ICollection<LU_tbl_City> LU_tbl_City { get; set; }
    }
}
