//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSIPortalContext : DbContext
    {
        public MSIPortalContext()
            : base("name=MSIPortalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LU_tbl_Country> LU_tbl_Country { get; set; }
        public DbSet<LU_tbl_ProductServiceType> LU_tbl_ProductServiceType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_PostCar> tbl_PostCar { get; set; }
        public DbSet<tbl_Question> tbl_Question { get; set; }
        public DbSet<tbl_UserPassword> tbl_UserPassword { get; set; }
        public DbSet<tbl_Post> tbl_Post { get; set; }
        public DbSet<LU_tbl_City> LU_tbl_City { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<LU_tbl_Category> LU_tbl_Category { get; set; }
    }
}
