<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SetupCategory.aspx.cs" Inherits="MSIPortal.SetupCategory" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    
         <div class="well">
       <%-- <form id="Form1" class="form-horizontal" runat="server">--%>
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
           <ContentTemplate>
       

        <h4>
            Category Setup</h4>
        
       
        <div class="control-group">
           
            <label class="control-label" for="inputPassword1">
                Category Tree </label>
           
           
            <div class="controls" style="margin-top:-15px;">
                <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" 
                    
                    onselectednodechanged="TreeView1_SelectedNodeChanged" Width="201px" >
                </asp:TreeView>
             </div>               
           
        </div>
        <div class="control-group">
               
                  <label class="control-label">Category Name </label>
               
            <div class="controls">
                <asp:TextBox ID="txtCategiryName" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ControlToValidate="txtCategiryName" runat="server" ForeColor="Red" ErrorMessage="Category name required"></asp:RequiredFieldValidator>
            </div>
        </div>


        <div class="control-group">
               
                  <label class="control-label">Sales/Service</label>
               
            <div class="controls">
                <asp:DropDownList ID="ddlSalesService" runat="server">
                </asp:DropDownList>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" InitialValue="000" ControlToValidate="ddlSalesService" runat="server" ForeColor="Red" ErrorMessage="Sales/Service required"></asp:RequiredFieldValidator>
            </div>
        </div>


        <div class="control-group">
            <div class="controls">
                <input type="hidden" name="email_create" value="1">
                <input type="hidden" name="is_new_customer" value="1">
                <asp:Button runat="server" class="btn btn-primary" type="submit" Text="Save" 
                    ID="btnSave" onclick="btnSave_Click"  />
            </div>
        </div>
        
        <div class="control-group">
            <asp:Panel ID="MessagePanel" runat="server" Visible="false">
                <label class="control-label"></label> 
                 <div class="controls">
                <asp:Label ID="lblError" runat="server" Text="Label" ForeColor="Red"></asp:Label>   
                 <asp:Label ID="lblSuccess" runat="server" Text="Label" ForeColor="Black"></asp:Label>       
                 </div>
            </asp:Panel>
        </div>   
           
           </ContentTemplate>
        </asp:UpdatePanel>

      
<%--        </form>--%>
    </div>
    
    
</asp:Content>
