//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public tbl_User()
        {
            this.tbl_Post = new HashSet<tbl_Post>();
        }
    
        public System.Guid UserID { get; set; }
        public string LoginName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RoleID { get; set; }
        public string CityID { get; set; }
        public bool IsActive { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual LU_tbl_City LU_tbl_City { get; set; }
        public virtual ICollection<tbl_Post> tbl_Post { get; set; }
        public virtual tbl_UserPassword tbl_UserPassword { get; set; }
    }
}
