//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        public System.Guid PostID { get; set; }
        public string CategoryID { get; set; }
        public string CityID { get; set; }
        public string PSTID { get; set; }
        public string PostTitle { get; set; }
        public string PostDescription { get; set; }
        public string ImageUrl { get; set; }
        public System.Guid PostingUserID { get; set; }
        public string ProviderFirstName { get; set; }
        public string ProviderLastName { get; set; }
        public string ProviderAddress { get; set; }
        public string ProviderEmail { get; set; }
        public string ProviderPhoneNo { get; set; }
        public bool Approved { get; set; }
        public int Rank { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual LU_tbl_ProductServiceType LU_tbl_ProductServiceType { get; set; }
        public virtual LU_tbl_City LU_tbl_City { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual LU_tbl_Category LU_tbl_Category { get; set; }
    }
}
