//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostCar
    {
        public string PostId { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string RegistrationYear { get; set; }
        public string BodyType { get; set; }
        public string Condition { get; set; }
        public string Transmission { get; set; }
        public string FuelType { get; set; }
        public string EngineCapacity { get; set; }
        public string Milage { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
